[package]
name = "tokenizers" 
version = "0.9.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.140"
tokenizers = {version = "0.20.0" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "decode_benchmark"
harness = false
