name: Lint Check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check Go Version
        run: go version >> $GITHUB_OUTPUT

      #- run: diff -u <(echo -n) <(gofmt -d .)
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          args: --enable=nolintlint,gochecknoinits,bodyclose,gofumpt --verbose

      - name: Install Rust minimal nightly (only for fmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
          profile: minimal
          components: rustfmt

      - name: Install Rust minimal stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: clippy

      - name: Check code formatting
        run: |
          cd lib/src
          cargo +nightly fmt --all -- --check

      - name: Check cargo clippy warnings
        run: |
          cd lib/src
          cargo clippy --workspace --all-targets --all-features -- -D warnings