name: Test
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
jobs:
  Build:
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x, 1.20.x, 1.21.x ]

        runtime: [ linux-x64, linux-arm64, linux-arm, osx-x64, osx-arm64 ]
        include:
          - runtime: linux-x64
            os: ubuntu-latest
            devScript: ./dev.sh

          - runtime: linux-arm64
            os: ubuntu-latest
            devScript: ./dev.sh

          - runtime: linux-arm
            os: ubuntu-latest
            devScript: ./dev.sh

          - runtime: osx-x64
            os: macOS-latest
            devScript: ./dev.sh

          - runtime: osx-arm64
            os: macOS-latest
            devScript: ./dev.sh

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - if: matrix.os == 'ubuntu-latest'
        run: sudo chown -R $(whoami):$(id -ng) ~/.cargo/

      - name: Install cargo-readme for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-readme

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.26.x'

      - name: Check cmake
        run: cmake --version

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Build And Install Library
        run: make build

      - name: Run Unit Test
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: go test . -v -race

      - name: Run Benchmark Test
        run: go test . -bench=. -benchmem -benchtime=10s
